import swaggerAutogen from "swagger-autogen";

export const doc = {
  info: {
    title: "Your API Documentation",
    description: "API documentation autogenerated by swagger-autogen",
  },
  host: "localhost:3000", // Set to your host
  schemes: ["http"],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./server.js"]; // You can point this to multiple route files

swaggerAutogen(outputFile, endpointsFiles).then(() => {
  require("./app"); // Start your app after generation
});
